dotenv: .env
wallet:
  from_key: ${PRIVATE_KEY}
networks:
  default:
    development #you can change here which network you want to run on when launching 'brownie run ...'
  goerli:
    eth_usd_price_feed_address: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork:
    eth_usd_price_feed_address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed_address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
dependencies:
  #- <organization/repo>@<version>
  # https://github.com/smartcontractkit/chainlink-brownie-contracts
    - smartcontractkit/chainlink-brownie-contracts@0.5.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'

